export { default as authRoutes } from './auth.mjs'
export { default as userRoutes } from './user.mjs'
export { default as lotteryRoutes } from './lottery.mjs'
export { default as lotteryResultRoutes } from './lotteryResult.mjs'
export { default as lotteryCheckHistoryRoutes } from './lotteryCheckHistory.mjs'
